### ISSUE TITLE
Výřez do stěny

### ISSUE THREAD

**Issue by tenhobi** [3DprintFIT/B182HW-Assignment#10]
Jak jde vidět z renderu, referenční řešení má asi výřez zasahující do "komínu":

![image](https://user-images.githubusercontent.com/5287596/57518041-77ede700-7318-11e9-8269-dde5c3546277.png)

avšak podle výkresů to chápu tak, že by měla být díra jen v té "stěně" (aneb jak to mám já):

![image](https://user-images.githubusercontent.com/5287596/57518051-7b816e00-7318-11e9-8a83-12cc531bb978.png)

Jak to má být tedy správně?

**Comment by hroncok** [comment]
Dobrá otázka. Ten výřez do komínu nezasahuje, pouze jede po jeho ploše. OpenSCAD to tam vybarví hezky zeleně, jakože je to difference, ale rozměr to nemá. Jsou tam jiné facety, ale na stejné „úrovni“.

![_](https://user-images.githubusercontent.com/2401856/57518758-13cc2280-731a-11e9-8d9c-d955db0d70ed.png)

Ta situace se dá nasimluovat takhle:

```scad
difference() {
    cube(50, center=true);
    translate([0,0,(50+35)/2]) cube(35, center=true);
}
```

![_](https://user-images.githubusercontent.com/2401856/57519013-ac62a280-731a-11e9-8135-6efc558d21a5.png)

**Comment by tenhobi** [comment]
OK, díky. :unicorn:

**Comment by hroncok** [comment]
Jdou s tím dělat kravinky.

![_](https://user-images.githubusercontent.com/2401856/57520452-fc8f3400-731d-11e9-88e9-35eaa744d2f8.png)

![_](https://user-images.githubusercontent.com/2401856/57520508-1f214d00-731e-11e9-9ecb-a0a1cd2c4325.png)
