### ISSUE TITLE
Mismatched or missing parameter name?

### ISSUE THREAD

**Issue by Adam95** [3DprintFIT/B182HW-Assignment#5]
In the base drawing there's a parameter `vertical_horizontal_smooth_offset` which is missing in the given module declaration. On the other hand there's a parameter `vertical_horizontal_rods_offset` which is missing in given drawings. Is this just a name mismatch or is something else missing?

![image](https://user-images.githubusercontent.com/1652026/55290240-165d6300-53d1-11e9-939d-e421b18c8f4b.png)

![image](https://user-images.githubusercontent.com/1652026/55290250-342ac800-53d1-11e9-8fd0-7d7b53a4b622.png)

Another small discrepancy I noticed is with the `vertical_rods_distance` which is called `vertical_rod_distance` in the module declaration.

**Comment by marekreimer** [comment]
Yeah, both of these are typos, I'll fix them as fast as I can.
Going forward the correct names wil be `vertical_horizontal_rods_offset` and `vertical_rods_distance` respectively.

**Comment by marekreimer** [comment]
Should be fixed.
