### ISSUE TITLE
Nezakótovaná výška endstopu u modulu motor

### ISSUE THREAD

**Issue by vadlemar** [3DprintFIT/B182HW-Assignment#8]
Výška této části se nedá ze zakótovaného výkresu určit.
Ze zadaných parametrů bych si tipnul že to bude mít co dělat s proměnnou která se ve výkresech nevyskytla ani jednou - endstop_distance_from_bottom_rod. Prosím o ujasnění.
![image](https://user-images.githubusercontent.com/47743307/57095779-f2fd3f00-6d13-11e9-8e8b-01cece5a5f3d.png)

**Comment by hroncok** [comment]
Je to `endstop_distance_from_bottom_rod`, vzdálenost od *spodní* (takže *vrchní*, součástka je vzhůru nohama) hladké tyče.

**Comment by marekreimer** [comment]
Doplneno, zaviram
