### ISSUE TITLE
Chyba v testu 'test09'?

### ISSUE THREAD

**Issue by Adam95** [3DprintFIT/B182HW-Assignment#9]
Narazil jsem na problém v testu _test09_, kde se volá:
```
/*
 * Testing custom values, motor
 */

overview_motor()
translate([-10,0,0]) scale(.8)
x_ends(
	body_height=80,
	motor_size=80,
	motor_hole_distance = 50,
	motor_offset = 20,
	show_idler = false);
```

Výsledek testu je na následujícím obrázku, kde se v mém renderu nezobrazuje endstop:

![image](https://user-images.githubusercontent.com/1652026/57194291-6e920280-6f45-11e9-8018-7136e838bc75.png)

Myslím si, že je to proto, že se zvýšila `body_height` z 60 na 80, ale nijak se nezměnila `endstop_distance_from_bottom_rod`. Viz ilustrace na dalším obrázku. Šedým obdélníkem je vyznačena vzdálenost `x_smooth_rod_distance`, červeným obdélníkem `endstop_distance_from_bottom_rod`. Je pak jasné, že se mi endstop napozicuje někam dovnitř toho tělesa.

![image](https://user-images.githubusercontent.com/1652026/57194332-e3653c80-6f45-11e9-9d16-ae03bcc09152.png)

Je dost možné, že jsem jen něco nepochopil v zadání, ale po kontrole vzdáleností těch děr na obě tyče a offsetu endstopu od horní tyče mi to prostě nevychází.

Nevíte, kde je chyba?

Díky.

**Comment by hroncok** [comment]
Asi opraveno, prosím o kontrolu.
